### ISSUE TITLE
particle effect not working

### ISSUE THREAD

**Issue by dogevspenguin** [NextStarIndustries/Next-Star-Industries#12]
I wan to create antimatter bomb,and you create mod so HOW TO MAKE PARTICLE EFFECT FOR BDArmrory

**Comment by NextStarIndustries** [comment]
You'll need to learn how to use Unity and Part Tools for that.

**Comment by NextStarIndustries** [comment]
I've modified the plugin to call an explosionfx in space. So if you create a particle system fx it'll use it now.

**Comment by dogevspenguin** [comment]
also why my blue(z) wont go up it just stay when i change the rotation

**Comment by NextStarIndustries** [comment]
Don't rotate the main gameobject only rotate the other so the explosion travels toward the z direction. BDAc will do the rest of the rotation stuff it'self. Hope this is helping.

**Comment by dogevspenguin** [comment]
OK thx great MOD BTW
