### ISSUE TITLE
Explosions and destructin physics don't work in 1.10.1

### ISSUE THREAD

**Issue by DATAEXPUNGED** [NextStarIndustries/Next-Star-Industries#29]

**Comment by DATAEXPUNGED** [comment]
Specifically for the nukes

**Comment by NextStarIndustries** [comment]
Do you have all the needed dependencies? Can you provide the log file, please?

**Comment by NextStarIndustries** [comment]
> Specifically for the nukes

Do you have all the needed dependencies? Can you provide the log file, please?
