### ISSUE TITLE
Loading screen stuck at YT1300_Lifepod

### ISSUE THREAD

**Issue by Schopfenheiser** [NextStarIndustries/Next-Star-Industries#31]
![image](https://user-images.githubusercontent.com/72718938/95698674-089ac600-0c75-11eb-9ee8-88a43befdb53.png)

KSP log file
https://drive.google.com/file/d/1XGW5sT5_uBepcJjJp3wCIzlb0nyc2QS6/view?usp=sharing

**Comment by Schopfenheiser** [comment]
Tried to delete the part folder and loading completed properly.

**Comment by NextStarIndustries** [comment]
> Tried to delete the part folder and loading completed properly.

I've went through the log and you have a serious problem with DarkMultiPlayer spamming the null refs. This will cause all model loading to slow and will actually be affecting your entire game play by causing the cpu to over work. The YT1300 does seem to stop but it's not actually, it's loading the texture slow which I've fixed now pending the next update hopefully this week. Try removing DarkMultiPlayer and see how you load up. You also have a major error that is stopping your loading and that's with that KNES config file as seen in the image above. Errors like that will freeze the game up at times.

**Comment by NextStarIndustries** [comment]
> ![image](https://user-images.githubusercontent.com/72718938/95698674-089ac600-0c75-11eb-9ee8-88a43befdb53.png)
> 
> KSP log file
> https://drive.google.com/file/d/1XGW5sT5_uBepcJjJp3wCIzlb0nyc2QS6/view?usp=sharing

[WRN 10:25:06.227] Cannot create config from file 'F:\Schopf\Games\Kerbal Space Program\Kerbal Space Program Shared Horizons\GameData\Knes\Compatibility\Tweakscale\000_CleanUp.cfg'.
[WRN 10:25:06.228] Cannot create config from file 'F:\Schopf\Games\Kerbal Space Program\Kerbal Space Program Shared Horizons\GameData\Knes\Compatibility\Tweakscale\001_ScaleExponents.cfg'.
[WRN 10:25:06.251] Cannot create config from file 'F:\Schopf\Games\Kerbal Space Program\Kerbal Space Program Shared Horizons\GameData\Knes\Compatibility\Tweakscale\Knes-Legacy_TweakScale.cfg'.
[ERR 10:25:07.942] Error: Empty part config file

[WRN 10:25:07.942] Cannot create config from file 'F:\Schopf\Games\Kerbal Space Program\Kerbal Space Program Shared Horizons\GameData\KSPMagnetoDrive\Resources\ACEGenerator.cfg'.
[WRN 10:25:24.614] Cannot create config from file 'F:\Schopf\Games\Kerbal Space Program\Kerbal Space Program Shared Horizons\GameData\TweakScale\Examples.cfg'.
These config files need corrected.

**Comment by NextStarIndustries** [comment]
> Tried to delete the part folder and loading completed properly.

You're also missing these dependencies. Install these first.
[LOG 10:25:26.474] AssemblyLoader: Loading assemblies
[WRN 10:25:26.475] AssemblyLoader: Assembly 'FShangarExtender' has not met dependency 'ToolbarController' V1.0.0
[WRN 10:25:26.475] AssemblyLoader: Assembly 'FShangarExtender' is missing 1 dependencies
[WRN 10:25:26.475] AssemblyLoader: Assembly 'PatchManager' has not met dependency 'ClickThroughBlocker' V1.0.0
[WRN 10:25:26.475] AssemblyLoader: Assembly 'PatchManager' has not met dependency 'ToolbarController' V1.0.0
[WRN 10:25:26.475] AssemblyLoader: Assembly 'PatchManager' is missing 2 dependencies
[WRN 10:25:26.475] AssemblyLoader: Assembly 'ResonantOrbitCalculator' has not met dependency 'ClickThroughBlocker' V1.0.0
[WRN 10:25:26.475] AssemblyLoader: Assembly 'ResonantOrbitCalculator' has not met dependency 'ToolbarController' V1.0.0
[WRN 10:25:26.475] AssemblyLoader: Assembly 'ResonantOrbitCalculator' is missing 2 dependencies
[WRN 10:25:26.475] AssemblyLoader: Assembly 'SCANmechjeb' has not met dependency 'MechJeb2' V2.5.0
[WRN 10:25:26.475] AssemblyLoader: Assembly 'SCANmechjeb' is missing 1 dependencies
[WRN 10:25:26.475] AssemblyLoader: Assembly 'SmartStage' has not met dependency 'ClickThroughBlocker' V1.0.0
[WRN 10:25:26.475] AssemblyLoader: Assembly 'SmartStage' has not met dependency 'ToolbarController' V1.0.0
[WRN 10:25:26.475] AssemblyLoader: Assembly 'SmartStage' is missing 2 dependencies
[WRN 10:25:26.475] AssemblyLoader: Assembly 'WernherChecker' has not met dependency 'ClickThroughBlocker' V1.0.0
[WRN 10:25:26.475] AssemblyLoader: Assembly 'WernherChecker' has not met dependency 'ToolbarController' V1.0.0
[WRN 10:25:26.475] AssemblyLoader: Assembly 'WernherChecker' has not met dependency 'ButtonManager' V1.0.0
[WRN 10:25:26.475] AssemblyLoader: Assembly 'WernherChecker' is missing 3 dependencies
