### ISSUE TITLE
Guns not doing any damage in 1.10

### ISSUE THREAD

**Issue by WhackadillyWoo** [NextStarIndustries/Next-Star-Industries#33]
I have the necessary prerequisites as far as I can tell, but the guns in the mod seem to be leaving bulletholes but not do any damage. The guns in stock BDAC work fine though. Any idea why this might be the case?

**Comment by NextStarIndustries** [comment]
I'll look at them and let you know. I've been adjusting some configs to use the new damage system and it could be that you're simply using one I haven't got updated yet. I have a plan to release another minor update by Friday to correct things.

**Comment by WhackadillyWoo** [comment]
That might be the case. Thanks for looking into it, keep up the great work!

**Comment by NextStarIndustries** [comment]
> That might be the case. Thanks for looking into it, keep up the great work!

After going through things it's because I don't have all the bullet configs done. It'll be updated in the next update release or watch for me to update the master branch. I keep this branch up to date with what I'm doing atm.
