### ISSUE TITLE
How to make particle effect go Z+ 

### ISSUE THREAD

**Issue by dogevspenguin** [NextStarIndustries/Next-Star-Industries#34]
SO i cannot find the old issue but i remember you tell me to make it move in Z+ direction,but IF i want a still particle effect,what should i do

**Comment by NextStarIndustries** [comment]
I believe you'll have to have them grab a random direction instead of the default Vector3. BDAc forces the default Vector3 to be the gloabal Z+.

**Comment by dogevspenguin** [comment]
it's not working.SO i make a particle effect that is composed of a KSP material and a texture,i export it in to my own KSP dir then i setup the path for my custom bomb but it's still doesn't work.My particle effect go o the Z direction

**Comment by NextStarIndustries** [comment]
Did you turn off any velocity setting on the particles in Unity?

**Comment by dogevspenguin** [comment]
I had a main gameobject that contain another gameobject the another game object contain a KSP emitter while the first gameobject contain KSP parttool i enable force over lifetime and velocity over lifetime
