### ISSUE TITLE
NSI DLL don't works with KSP 1.10.1

### ISSUE THREAD

**Issue by kurimanju-dev** [NextStarIndustries/Next-Star-Industries#35]
Today I downloaded the latest version of NSI via GitHub. It also said in Curseforge that you have to download Kopernicus and Kerbal Joint reinforcement. I did that too. Afterwards I installed all mods properly. But in the end it indicated that the following DLL was not compatible with the current version of KSP: "GameData/NSI/Plugins/NextStarIndustries.dll/.
if I have installed anything wrong or forgot to install it, I would appreciate an answer. :)

I apologize for my English

![Screenshot (47)](https://user-images.githubusercontent.com/73285163/96861709-c20f4d80-1464-11eb-9368-43f3c082d641.png)

**Comment by NextStarIndustries** [comment]
Not sure why you have that error as it's completely written around KSP 1.10.1. Is your BDAc v1.3.4? Kopernicus and KJR are only needed for certain parts of the Star Wars stuff. Anyway you could upload your log file somewhere so I can take a look at that? My install is loading fine. I have seen this happen with miniavc being installed.

**Comment by kurimanju-dev** [comment]
Oh god, i think i've Forgot to install BDA.... Sorry XD

**Comment by kurimanju-dev** [comment]
But Thanks for the help, i will try it again 👍

**Comment by kurimanju-dev** [comment]
It worked, thank you so much!!!
